### PR TITLE
fix styleguidist configuration so that everything gets its own page

### PR DESCRIPTION
**Pull request by cshepherd**
Signed-off-by: Christopher Shepherd <christopher@reactioncommerce.com>
Closes: https://github.com/reactioncommerce/reaction-component-library/issues/422
Impact: **minor**  
Type: **bugfix**

## Component
No components or dependencies changed, just updated styleguidist.config.js so that every topic gets its own page instead of rendering the whole style guide on one huge slow page

### CODE REVIEW

**Comment by rc-publisher** [comment]
🚀 Preview deployed

Built with commit c90a25284e09f6bf4d8249045c48cb2ed81d92bd

https://deploy-preview-423--stoic-hodgkin-c0179e.netlify.com

**Comment by machikoyasuda** [comment]
Confirmed: 
Screen Shot 2019-07-19 at 11 10 29 AM

Lint failed tho!

**Comment by machikoyasuda** [comment]
@cshepherd be careful using the word `fix` in non-npm-module code-fix commits. (like any work on Styleguidist itself). i dont think this pr will trigger a release, cos that requires `fix:` though

**Comment by machikoyasuda** [comment]
Merging.

**Pull request merged**
