### PR TITLE
feat: 346 nnnnat multi select

### LINKED ISSUE #346: MultiSelect component
# MultiSelect

### Summary description of UI component
Similar to `Select` component, but for when multiple values can be selected and the `value` is expected to be an array.

### Rationale for why this component is necessary
To select more than one value for fields

### Expected use cases
Lots of fields when defining shipping rules, tax rules, etc. as admin

### Images / Designs of UI component in context
https://zpl.io/295jjed

Most styles should be the same as copied from `Select`, but some additional styles might be needed for the selected items that appear in the field with `x`, and verify that it looks correct with lots of items shown.

### React State
Same as in `Select` component. Only difference is `value` prop will be an array.

### Data Fetching
None

### State Store
None

### Routing / Query String
None

### Render Criteria
Same as in `Select` component.

#### Desktop, Tablet, Mobile
Same as in `Select` component.

## UI States
Same as in `Select` component.

## Work
Copy `Select` to `MultiSelect`, add `isMulti` prop on the `react-select` component, and update it to work with array value and have any additional necessary styles to match Zeplin designs.

### PR DESCRIPTION
**Pull request by nnnnat**
Resolves #346 
Impact: **minor**  
Type: **feature**

## Component
Based on this [spec](https://github.com/reactioncommerce/reaction-component-library/issues/346)

## Screenshots
screen shot 2018-11-01 at 4 40 30 pm

## Breaking changes
N/A

## Testing
1. View [MultiSelect](https://deploy-preview-353--stoic-hodgkin-c0179e.netlify.com/#!/MultiSelect) docs verify working/looks as expected.

### CODE REVIEW

**Comment by rc-publisher** [comment]
🚀 Preview deployed

Built with commit f7de4050a037811cbc335aeb6860650f8a943d4c

https://deploy-preview-353--stoic-hodgkin-c0179e.netlify.com

**Comment by nnnnat** [comment]
@cassytaylor this PR is still WIP but can you take a quick look at the "remove icon" hover style?
https://deploy-preview-353--stoic-hodgkin-c0179e.netlify.com/#!/MultiSelect

**Comment by cassytaylor** [comment]
@nnnnat cool, I hadn't thought of styling the hover that way - I think it looks good!!

**Pull request merged**
