### PR TITLE
Fix: use correct image sizing in grid for portrait images

### LINKED ISSUE #293: Grid images not sized correctly
Type: **minor**

**Describe the bug**
Some images in the grid are not sized correctly. Landcape images are fine, but portrait images appear as rectangles inside the square. See the screenshot below.

**To Reproduce**
1. Visit the starterkit with the sample data
2. Observe portrait images not being sized correctly

**Expected behavior**
If an image is landscape, nothing needs to be changed. But if an image is portrait, the `fit` prop on the `ProgressiveImage` component within the grid should be set to `contain`.

**Screenshots**
incorrect-image-sizing

### PR DESCRIPTION
**Pull request by dancastellon**
Resolves #293
Impact: **minor**  
Type: **bugfix**

## Component
Portrait images were not being sized correctly in `CatalogGrid`.

### Before
incorrect-image-sizing

### After
correctly-sized-images

## Breaking changes
None

## Testing
1. View the "Cover vs fit" example for `CatalogGrid` and confirm both images are sized correctly.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit 0f54e4f601d71dd1ff298285eadd64bf35e36d64

https://deploy-preview-294--stoic-hodgkin-c0179e.netlify.com

**Comment by spencern** [comment]
@aldeed @rymorgan is this how it should work? We're losing fidelity here by cropping the image.

**Comment by rymorgan** [comment]
@spencern Yea, honestly I've never liked how it looks when we auto crop some of the images. My intention with the grid was that it would do what it was doing before this fix. In other words, that it would keep the ratio of the image and leave the extra space in the square container. 

I'm somewhat conflicted though because - 

- I don't see this being a huge issue for most single tenet bigger shops as they will have a set ratio and have a system for producing, cropping, and making images all the exact same size. their images. 
- It could become an issue with marketplaces though. I'm looking at etsy and it seems they do what we are doing here w/ containing images. 
- Is it easier for them to implement either an all vertical or all horizontal grid w/ the way we've coded it here?

**Pull request merged**
