### PR TITLE
(feat): 256 nnnnat address book

### LINKED ISSUE #256: Create AddressBook component
# AddressBook
## Overview / Summary
Create a component that will permit a user to enter a new address,  to pick from an entered address or show an automatically validated suggested address. This component will be the wrapper/state manager for the `AddressForm`, `AddressSelect` and `AddressReview` components.

### Expected use cases
* If the user had no addresses saved then the `AddressBook` should show the `AddressForm`.
* Once the user has entered an address and has been returned with validation/location issues the `AddressBook` should show the `AddresReview` component.
* If the user has 1 or more valid addresses saved then the `AddressBook` should show the `AddressSelect` component.

### Images / Designs of UI component in context
`AddressSelect`
screen shot 2018-08-27 at 10 47 13 am

`AddressForm`
screen shot 2018-08-27 at 10 47 29 am

`AddressReview`
screen shot 2018-08-27 at 10 47 54 am

### React State
Most likely need to keep track of an `activeAddress` if the user selects one for editing.
Also an `isSaving` to disable the addressForm while it's sending the value to the API.

### Data Fetching
This component may be responsible for handling address location validation so it knows when to show the `AddressReview` component and have a way to get the "suggested address" data.

### PR DESCRIPTION
**Pull request by nnnnat**
Resolves #256 
Impact: **major**  
Type: **feature**

## Component
* Created an `AddressBook` component that will manage which address UI needs to be active and to provide a standard way of capturing each address UI's interaction.
* Started an `Accordion` component that: 
   * Displays a label and details in a similar fashion to the `selectableItem`
   * Displays a "child" in the content area.
   *  Toggle "expanded" state.

* Started an `AddressReview` component and added it to the component's context. This component will be finished in another PR.

## Breaking changes
N/A

## Testing
**Accordion**
*NOTE* The `Accordion` component is MVP just to get the `AddressBook` moving. It will need some enhancements to be used in other situations. 
1. Verify this works and looks as expected.

**Address Book**
1. Verify the "Add new address" UI is working and looks as expected.
    * Enter a new address and see it logged in the browser console.
2. Verify the "Address Overview/Book" UI is working and looks as expected.
    * Edit an existing address and see the changes in the browser console.
    * Click "Delete address" and see the select address data in the browser console.
    * Click "Add new address" button to see view toggle, click "cancel" to see it toggle back.
    * Click "Add new address" enter an address, submit and see the new address values in the browser console.
3. Verify that if a `validatedValue` address is provided that the `AddressReview` (finishing in the following PR) displays.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit ccc8af0a3ede1e4a1094722f1ece43760baa6e0a

https://deploy-preview-262--stoic-hodgkin-c0179e.netlify.com

**Comment by kieckhafer** [comment]
Font size and color is a bit off in the Accordion. Font size should be 14px, and color should a bit lighter. @aldeed's changes to the way we are doing the style variables may affect how this needs to be done.

Current:
addressbook_ _reaction_design_system


Design:
zeplin

**Comment by nnnnat** [comment]
@kieckhafer  I've addressed the style issues and updated a few things and refreshed the docs. I've now got an implementation example of the `AddressBook` you should be able to test everything there.

**Comment by nnnnat** [comment]
@kieckhafer you'll need to test the add/edit/delete actions on the implementation example at the bottom of the page. The other examples only have no-op callbacks.

**Comment by kieckhafer** [comment]
@nnnnat I'm still seeing the error

```
index.js:2178 Form "onSubmit" function error: TypeError: Cannot read property 'then' of undefined
    at AddressBook._this.handleEditAddress (AddressBook.js:210)
    at onSubmit (AddressBook.js:247)
    at Form.js:244
```

When I try to update an existing address. The update works (as does everything else in testing), this seems to be the only issue.

**Comment by nnnnat** [comment]
@kieckhafer I wasn't returning the Promises in the example handlers. Should be working now

**Comment by machikoyasuda** [comment]
I just always wanted an excuse to use this emoji: 📇

**Pull request merged**
