### PR TITLE
fix: security bulk dep update

### PR DESCRIPTION
**Pull request by focusaurus**

### CODE REVIEW

**Comment by focusaurus** [comment]
@mikemurray could you take a look at the netlify error. Not sure what this means but I think the failure is these lines:

```
1:10:39 PM:  FAIL  Failed to compile
1:10:39 PM: multi @babel/polyfill ./styleguide/src/styles.css ./node_modules/react-styleguidist/lib/client/index
1:10:39 PM: Module not found: Can't resolve '@babel/polyfill' in '/opt/build/repo'
1:10:39 PM: error Command failed with exit code 1
```

**Comment by focusaurus** [comment]
Um, has lint been neglected on this project? 977 errors in CI.

**Comment by mikemurray** [comment]
@focusaurus The majority of the `lint` issues seem to be the following....

```
node/no-unpublished-import
node/no-unsupported-features/es-syntax
```

There was a change to the shared eslint package we use that made these default to errors. They aren't applicable to`styleguidist` and the actual `package` must have unpublished imports because it relies on the project it's included in to install the correct peer dependencies.

We disabled them in Catalyst, https://github.com/reactioncommerce/catalyst/blob/master/package.json#L39-L40

---

The other test failures seem to be outdated snapshots.

**Comment by focusaurus** [comment]
Will revisit another time. With updated deps and turning off the new rules we don't want, there's ~25 new eslint errors to work through.

**Pull request closed without merging**
