### PR TITLE
feat: AddressReview component

### LINKED ISSUE #122: Address Validation Reconciliation Component
# Address Validation Reconciliation

## Overview / Summary
Create a component that will permit a user to pick from an entered address or a automatically validated suggested address. The entered address should have the fields that may be incorrect or incomplete highlighted. The component should provide a button to edit the entered address and a button to confirm a selected address.

### Summary description of UI component
This component is essentially a form with a radio input and styled labels.

### Rationale for why this component is necessary
This component is necessary for reconcilling a customer entered address with an address validation service and providing a way for the customer to edit their address, keep their address as it was entered, or to use a suggested address from an address validation service.

### Expected use cases
This component will be used by the address book when an address validation service plugin is in use. When a customer enters an address that cannot be validated, the address validation reconciliation component should be shown. Once a customer has selected a valid address or edited an address to make it valid, the address should be added to the address book or cart as necessary

### Images / Designs of UI component in context
image

### JSX
This component exists in the Meteor Reaction app already and was updated in #4086 to match these designs. I believe we will just need to port the existing component to the Component Library
See https://github.com/reactioncommerce/reaction/pull/4086#issuecomment-405134774

```js
// Invalid field information could potentially be passed inside of the address object if that makes more sense here.
propTypes: {
  addressEntered: Reaction.PropTypes.address,
  addressSuggested: Reaction.PropTypes.address,
  invalidFields: ["region", "postal"]
  onSubmit: PropTypes.func,
  onEdit: PropTypes.func,
  warningDescription: PropTypes.string
}
```

### Render Criteria
This component should be rendered when a user attempts to create a new address and and the address creation is rejected and a suggested address correction is supplied instead.

### Normal
The normal state for this component is really a specific error state for the address book involving a new address that has been entered but caught during a validation process
https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b197a1ca2d5663159876954

It appears that the "Suggested address" should be selected by default when this component is initially rendered

There are no additional states for this component in the designs.

### PR DESCRIPTION
**Pull request by nnnnat**
Resolves #122 & #277 
Impact: **major**  
Type: **feature**

## Component
**AddressReview**
  *  Based on this [spec](https://github.com/reactioncommerce/reaction-component-library/issues/122)

**Address**
  *  Created an Address component that displays an Address

**SelectableList Enhancement** 
  *   Adds `isHorizontal` prop: Updated to allow a horizontal layout along with the vertical style.
  *   Adds `isStacked` prop: Updated to allow `detail` to display stacked under the label along with the right/left aligned.

## Screenshots
screen shot 2018-10-18 at 1 48 41 pm
⚠️ The alert is not part of this component. The alert will be worked on next. This alert is just a mock-up.

## Breaking changes
N/A

## Testing
1. **AddressReview**: https://deploy-preview-336--stoic-hodgkin-c0179e.netlify.com/#!/AddressReview
    * Open broswer console and test the example implamentation towards the bottom of the page.
    * You should see the selected address object in the console after you click submit.
2. **Address**: https://deploy-preview-336--stoic-hodgkin-c0179e.netlify.com/#!/Address
    * Verify it's workings and looks as expected.
3. **SelectableList**: https://deploy-preview-336--stoic-hodgkin-c0179e.netlify.com/#!/SelectableList
    *  Verify the `isHorizontal` prop is working and looks as expected. 
3. **SelectableItem**: https://deploy-preview-336--stoic-hodgkin-c0179e.netlify.com/#!/SelectableItem 
    * Verify the `isStacked` prop is working and looks as expected. (see Address as detail header)

### CODE REVIEW

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit d0b023c4fc51a13a41f42bfd8caddf1c555f710e

https://deploy-preview-336--stoic-hodgkin-c0179e.netlify.com

**Comment by nnnnat** [comment]
@cassytaylor I've made a few updated to the [Address](https://deploy-preview-336--stoic-hodgkin-c0179e.netlify.com/#!/Address) component since you last reviewed if you don't mind taking another quick look.

**Comment by nnnnat** [comment]
@cassytaylor the [Address](https://deploy-preview-336--stoic-hodgkin-c0179e.netlify.com/#!/Address) has been updated since you last reviewed so you might want to take a quick look again.

**Comment by cassytaylor** [comment]
@nnnnat thanks for the heads up - looks good to me!

**Pull request merged**
