### PR TITLE
(feat): added addressName optional field to AddressForm

### LINKED ISSUE #229: Add optional "Address Name" field to AddressForm component
Type: **minor**

**Enhancement**
We'd like to have the ability to let users name or label the different addresses they may add. To do this we'll need to add another optional field to the `AddressForm` component possibly named `addressName`.

**Expected behavior**
The `AddressForm` component will show an `addressName` field if the `shouldShowNameField` prop is `true`. The default is to not show the field.

**Additional context**
@cassytaylor this new field isn't in any of the designs, I can add it to the top of the form component for now and we can work out the design during the PR review.

### PR DESCRIPTION
**Pull request by nnnnat**
Resolves #229 
Impact: **minor**  
Type: **feature**

## Component
Added an optional text field that can capture an "Address Name" to the `AddressForm`.

## Screenshots
screen shot 2018-08-20 at 4 56 12 pm

## Breaking changes
N/A

## Testing
1. On staging go to the bottom of the `AddressForm` docs and add `shouldShowAddressNameField` prop to the `<AddressForm />` in the example implementation editor.
2. Fill out the `AddressForm` with an "Address Name" and submit the form.
3. In the browser console, you should see the address object with the `addressName` property.

@aldeed  I tagged you as a reviewer just to verify my address property name "addressName" would be OK.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit 2f4a10026746a26c4b3590a536ae248d23079968

https://deploy-preview-244--stoic-hodgkin-c0179e.netlify.com

**Comment by aldeed** [comment]
@nnnnat Seems fine.

@cassytaylor The primary purpose in mind is for the shop address book. We will eventually need to support multiple "ships from" addresses, so the idea is that an operator would be able to select one of these addresses when editing a variant. For example, you'd add an address to the shop's address book with the name "Warehouse A", and then when editing the variant, you'd select "Warehouse A" for the "Ships from" field.

But in the more immediate term, we might consider showing this, if set, on the [address book select list](https://zpl.io/b6MwwBj). For example, someone with an account might save it with the name "Home", so we could have the list item say "Home (2300 Buckwheat Ave)" instead of the full address. I'd leave that up to you to decide.

**Comment by aldeed** [comment]
Why do we have placeholders that are the same as the labels? In this case, a placeholder like `"Home", for example` would be better. However, it might say that for the account address book but say `"Headquarters", for example` for the shop address book. So maybe there should be another prop called `addressNamePlaceholder` allowing the parent to set the placeholder?

**Comment by cassytaylor** [comment]
Cool. I'd be down to surface the address names in the address book like you mentioned above, @aldeed. And +1 on using different placeholders for that field based on the context - I think that would improve its usage! (Also, @nnnnat should the field label say "Optional")?

**Comment by nnnnat** [comment]
@aldeed & @cassytaylor  I've updated the form to now have an `isAddressNameRequired` prop that can toggle the "Address Name" field to be either required or optional for the form.

**Pull request merged**
