### PR TITLE
Add ActionIncomplete component

### LINKED ISSUE #116: Checkout Action Incomplete
# Checkout Action Incomplete

### Summary description of UI component
This component should be rendered for any incomplete checkout actions.

### Rationale for why this component is necessary
This component abstracts the incomplete checkout action UI.

### Expected use cases
This component will be used in the checkout process for any incomplete checkout actions

### Where this component should be created
This component should be created in the component library

### Images / Designs of UI component in context
image

```jsx
// Pseudo-markup for the Completed Checkout Action
<div>
  <span>1.</span>
  <span>Label</span>
</div>
```

### Props
```js
propTypes: {
  stepNumber: PropTypes.string,
  label: PropTypes.string
}
```

### Render Criteria
This component will be rendered for each incomplet checkout action

#### Normal
This prop only exists in a Normal state. Render the step number and the label
There are many Zeplin examples, any UI with an incomplete checkout step.
https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b2191dba2352bfa33838401

In this example, the Shipping method, Payment information, and Review and place order are all incomplete.

### PR DESCRIPTION
**Pull request by willopez**
Resolves #116 
Impact: Minor
Type: Feature

## Component
Adds `ActionIncomplete` component that will be used in the checkout process to display incomplete steps.

## Testing
1. Verify component matches designs

### CODE REVIEW

**Comment by rymorgan** [comment]
@kieckhafer I think this component will be specific to check out.

**Comment by rymorgan** [comment]
Also, sorry for the confusion here between the designs but the ActionIncomplete font size should be 14. Nothing y'all missed or did wrong but something I missed when reviewing Cassy's designs.

**Comment by willopez** [comment]
@kieckhafer I'll change the name to `CheckoutActionComplete`

**Comment by willopez** [comment]
@rymorgan Currently the default font size for all components is 16, it's set in the theme. Should it be 14px as default for all components?

**Comment by rymorgan** [comment]
@willopez No, the default size should stay 16. I was assuming we had this type scale available to us (though I do realize we were a little late in communicating the scale we wanted). 

screen shot 2018-07-13 at 11 06 13 am

https://zpl.io/VDz7kQJ

**Comment by willopez** [comment]
@rymorgan got it, thanks for the info.

**Comment by rymorgan** [comment]
@willopez Are you using our type scale? Or are you leaving it 16?

**Comment by willopez** [comment]
Using the type scale, so the body text is set to 16, so that is correct. We will use the type scale for all other elements.

**Comment by kieckhafer** [comment]
@willopez we have the `font_size_small` variable to use for size `14`, since we use it frequently.

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit 532d70a0b89b330e07c33ac3432e1f19c25d3e00

https://deploy-preview-129--stoic-hodgkin-c0179e.netlify.com

**Comment by willopez** [comment]
@kieckhafer ready for another review

**Comment by willopez** [comment]
adding @rymorgan and @machikoyasuda for design and docs review and to test out the auto deploy

**Comment by willopez** [comment]
@machikoyasuda I added to more commits, after the previous auto deploy, and don't see another auto deploy, did am I missing something?

**Pull request merged**
