### PR TITLE
Skip company when validating filled fields

### LINKED ISSUE #416: Skip validation of "company" in Shipping checkout step
Type: **breaking**

**Describe the bug**
As described in https://github.com/reactioncommerce/example-storefront/issues/494 the previously saved shipping address can't be edited and saved in checkout.

**To Reproduce**
1. Add Products to cart and checkout
2. Add a shipping address
3. Reload the page
4. Edit the address, notice that the save Button always stays greyed out.

**Expected behavior**
As all visible fields seem valid to the user, the Save button should be enabled.

**Screenshots**

**Desktop/Smartphone:**
This error is device independent

**Additional context**
A saved address which is then fetched after after reload will contain `company` with a value of `null`, therefore making the validation [isFormFilled](https://github.com/reactioncommerce/reaction-component-library/blob/5e8ec3676cfcd27020f1878b8cf6c6ac3c5c02aa/package/src/components/ShippingAddressCheckoutAction/v1/ShippingAddressCheckoutAction.js#L182) fail.

**Possible solution**
Skip `company` when checking the fields for `null`, just like it is done with `address2 `

### PR DESCRIPTION
**Pull request by janus-reith**
As described Here: https://github.com/reactioncommerce/reaction-component-library/issues/416

Resolves #416
Impact: **|major**  
Type: **bugfix**

## Component
Nothing relevant here.

## Screenshots
Not a new or visually altered component.

## Testing
1. Add a product and go to checkout in the storefront
2. Add a shipping address
3. Reload the page
4. Notice that the shipping address can be updated properly now.

### CODE REVIEW

**Comment by rc-publisher** [comment]
🚀 Preview deployed

Built with commit 589628f4f238d53aa28cec32235efd8e64b289b8

https://deploy-preview-417--stoic-hodgkin-c0179e.netlify.com

**Comment by janus-reith** [comment]
Anything to do on my side to fix that failing CircleCI build?

**Comment by aldeed** [comment]
@janus-reith I think it's just a permission failure due to trying to run on your fork. We can ignore it.

**Comment by aldeed** [comment]
@spencern Does someone have permission to merge this with the failing snyk test? It seems like snyk can't run on a fork PR?

**Pull request merged**
