### PR TITLE
Update to latest eslint config and fix issues

### PR DESCRIPTION
**Pull request by aldeed**
Impact: **minor**  
Type: **chore**

## Changes
Update to latest Reaction eslint config and fix all errors and warnings that resulted

## Breaking changes
None

## Testing
Verify that eslint passes

### CODE REVIEW

**Comment by rc-publisher** [comment]
🚀 Preview deployed

Built with commit 1198e765e42b442634568376948c0dc08f2a9e41

https://deploy-preview-394--stoic-hodgkin-c0179e.netlify.com

**Comment by machikoyasuda** [comment]
Testing:
- Read over JSDoc comments
- I built the PR branch and ran:
```$ docker-compose run web yarn run lint:eslint
yarn run v1.9.4
$ eslint .
Done in 25.43s.```

👍

**Comment by machikoyasuda** [comment]
This is a _chore_ PR so it will not trigger a new build.

**Pull request merged**
