### PR TITLE
fix: remove yarn.lock file

### LINKED ISSUE #412: Remove yarn.lock so applications get security fixes
Type: **minor**

**Describe the bug**

If this library is intended to be used as an npm dependency, including a `yarn.lock` is not something we should do. That will prevent semver minor patches from getting installed in the applications using this library.

### PR DESCRIPTION
**Pull request by focusaurus**
This does not belong in a library.
It prevents security fixes flowing through to applications.

Resolves #412 

I confirmed after removing `yarn.lock` and running `snyk test`, there are no vulnerabilities at the moment.

```
snyk test
/ Analyzing npm dependencies for package.json

Testing /home/plyons/github/reactioncommerce/reaction-component-library...

Organisation:    focusaurus
Package manager: npm
Target file:     package.json
Open source:     no
Project path:    /home/plyons/github/reactioncommerce/reaction-component-library
Local Snyk policy: found

✓ Tested 100 dependencies for known vulnerabilities, no vulnerable paths found.
```

### CODE REVIEW

**Comment by nnnnat** [comment]
@focusaurus snyk looks to be failing in circle

**Comment by focusaurus** [comment]
@nnnnat think you could help out here with the test failures? I don't understand why this would be so brittle that removing the `yarn.lock` files would suddenly cause CI tests to start failing.

**Comment by nnnnat** [comment]
@focusaurus this is kinda bizarre, part of the failures look like snapshots that just need updated. I have been unable to get the test to run correctly locally. I've tried both in and out of docker with no luck. I think I could figure out the test issue if you could help me with my docker/host machine issues.

**Comment by focusaurus** [comment]
Hmm so netlify build is now failing with `11:48:01 AM: /usr/local/bin/build: line 34: yarn: command not found`. Maybe they were seeing the yarn.lock file and installing that automatically and now they are not?

**Comment by focusaurus** [comment]
Turning into a big mess. Don't worry, I'll rebase and tidy up once things go green.

**Comment by rc-publisher** [comment]
🚀 Preview deployed

Built with commit ec4ff2fac4fe127b7a0406ee1b26c98e7ab0b980

https://deploy-preview-413--stoic-hodgkin-c0179e.netlify.com

**Comment by focusaurus** [comment]
OK finally passing all CI checks. I'll rebase the commits and try to make it coherent.

**Comment by focusaurus** [comment]
OK I rebased and force pushed a tidier set of commits. Feel free to rain your reviews upon me.

**Pull request merged**
