### PR TITLE
Chore aldeed project changes

### PR DESCRIPTION
**Pull request by aldeed**
- Updated some packages. Add Jest, snapguidist
- Added our lint rules, and a precommit hook to run lint + test
- Added the beginnings of a Button component to show proposed patterns for styles, tests, and helper functions (Not complete. To be finished later.)
- Added a style guide section to show to do that
- Added a CSS stylesheet with comment-separated sections in it and a few example styles
- Explain things in readme

### CODE REVIEW

**Comment by zenweasel** [comment]
@aldeed Looks like there are lint errors and tests are failing

**Comment by aldeed** [comment]
@zenweasel Where do you see that? I see a few things mentioned on Codacy but none of those are actual issues. Since there is a precommit hook that runs lint and tests, it should be impossible for there to be lint or test issues. :)

**Comment by zenweasel** [comment]
Just talking about right in the PR summary where it's saying it can't merge because of code quality issues.



Tests seem to be passing now though

**Comment by aldeed** [comment]
@zenweasel Yes, I don't know how to dismiss codacy issues if they aren't real issues. It seems it's not using the lint config from the repo or something.

**Pull request merged**
