### PR TITLE
docs: expand and update docs

### PR DESCRIPTION
**Pull request by aldeed**
Moved docs out of README and into /docs, and expanded on some missing info.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
Aside from this PR, I don't think pre-commit hooks are working for me. Are there installation instructions for this? I tested it by committing a file with single-quotes and git allowed me to do so.

**Comment by machikoyasuda** [comment]
Rebase with master + merge 👍

**Comment by machikoyasuda** [comment]
I don't see a pre-commit.sh file anywhere in the repo. Maybe it's only in your local dir?

**Comment by aldeed** [comment]
@machikoyasuda Hmm, that has been in the readme since the beginning, but I think maybe I tried using pre-commit and then removed it because it wasn't working correctly? Anyway we aren't using it in other repos yet, so for now I just removed that part of the readme. Maybe we'll do something like that in all our repos eventually.

**Pull request merged**
