### PR TITLE
fix: resolve several linting issues

### PR DESCRIPTION
**Pull request by spencern**
Resolves un-ticketed linting issues
Impact: **minor**  
Type: **bugfix**

Fixes linting issues across several components
fix: remove a trailing comma from AddressBook
fix: remove trailing comma from CartSummary
fix: eliminate lint issues CheckoutEmailAddress
fix: eliminate lint issues in Field component
fix: eliminate lint issues in MiniCartSummary
fix: eliminate lint issues in StripePaymentInput
fix: make postbuild recursivelyChangeExt follow consistent-return

### CODE REVIEW

**Comment by rc-publisher** [comment]
🚀 Preview deployed

Built with commit 3a358bbac3a9c0cda60024d9cc1ea4b985e70acc

https://deploy-preview-469--stoic-hodgkin-c0179e.netlify.com

**Comment by aldeed** [comment]
Unit test snapshots still failing but that's an existing issue that will be fixed in a separate PR. @spencern OK to merge this.

**Comment by spencern** [comment]
I fumbled with the snapshots for a bit, but I'm still having trouble getting this project running tests locally.

**Pull request merged**
