### PR TITLE
chore: rename title to Storefront Component Library

### LINKED ISSUE #424: Copy/Naming: Remove all references to "Reaction Design System"
It's not a thing. It's all over this app.

### PR DESCRIPTION
**Pull request by machikoyasuda**
Signed-off-by: Machiko Yasuda <machiko@reactioncommerce.com>

Resolves #424 
Impact: **major**  
Type: **docs|chore**

## Docs
- Rewrites `Introduction.md` entirely
- Change title of `README.md`

## Site
- Change title to `Storefront Component Library | Reaction Commerce`
- Update name in `manifest.json`

## Code
- Change .SVGs in tests, docs to Reaction Storefront Component Library logo
- Update snapshot tests that used the `logo.svg` file
- Update name + description in `package.json`
## Images
- [x] - Need a new logo @rymorgan 

## Overall new look

Screen Shot 2019-07-31 at 3 56 39 PM

### CODE REVIEW

**Comment by rc-publisher** [comment]
🚀 Preview deployed

Built with commit 97f63d4023de9df557223f64fef9c77b04ac8ca6

https://deploy-preview-426--stoic-hodgkin-c0179e.netlify.com

**Comment by rc-publisher** [comment]
🚀 Preview deployed

Built with commit d22690096c248ad9222a745bba9dac51bd95c998

https://deploy-preview-426--stoic-hodgkin-c0179e.netlify.com

**Comment by machikoyasuda** [comment]
@rymorgan This is ready for a full review:

- Full site: https://deploy-preview-426--stoic-hodgkin-c0179e.netlify.com/
- README: https://github.com/reactioncommerce/reaction-component-library/blob/424-docs-naming/README.md

@nnnnat Just tagged you for the `package.json` + `manifest.json` stuff.

I checked https://www.npmjs.com/package/@reactioncommerce/components and it looks like all the language there is good to go.

**Comment by machikoyasuda** [comment]
Lastly, I need @spencern to update the info at the top of the GitHub repo main page:

`Example Storefront Component Library: A set of React components for the Example Storefront`

**Comment by machikoyasuda** [comment]
@nnnnat good call - updated!

**Pull request merged**
