### PR TITLE
feat: CheckoutActionComplete component

### LINKED ISSUE #112: Checkout Action Complete
# Checkout Action Complete

### Summary description of UI component
This component should be rendered for any completed checkout actions.

### Rationale for why this component is necessary
This component abstracts the completed checkout action UI.

### Expected use cases
This component will be used in the checkout process for any completed checkout actions

### Where this component should be created
This component should be created in the component library

### Images / Designs of UI component in context
image

```jsx
// Pseudo-markup for the Completed Checkout Action
<div>
  <span>Label</span>
  <div>Content</div>
  <Button>Change</Button>
</div>
```

### Props
```js
propTypes: {
  label: PropTypes.string,
  content:PropTypes.instanceOf(Element),
  onChange: PropTypes.func
}
```

### Render Criteria
This component will be rendered for each completed checkout action

#### Normal
This prop only exists in a Normal state. Render the label, the content and the `change` button.
There are many Zeplin examples, any UI with a completed checkout step.
https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f47216618fd82ceea667

In this example, the Shipping address and the Shipping method actions are both complete.

### PR DESCRIPTION
**Pull request by kieckhafer**
Resolves #112
Impact: **minor**  
Type: **feature**

## Component
This component will be used in the checkout process for any completed checkout actions. This component requires a wrapper component to determine the logic whether it will show or not. That logic is not internal.

## Screenshots
Desktop:
checkoutactioncomplete_ _reaction_design_system

Mobile:
checkoutactioncomplete_ _reaction_design_system_and_checkoutactioncomplete_ _reaction_design_system

## Breaking changes
None

## Testing
1. See that the CheckoutActionComplete component matches designs:
[Desktop](https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f47216618fd82ceea667).
[Mobile](https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/screen/5b02f55c7e031a4693c64adc)

### CODE REVIEW

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit 7e5fb9c743a239fcc6daa81532f9263d5f3c8a02

https://deploy-preview-131--stoic-hodgkin-c0179e.netlify.com

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit 11c77c75b5fb8738366667b14494436f017a5217

https://deploy-preview-131--stoic-hodgkin-c0179e.netlify.com

**Comment by willopez** [comment]
There is prop validation error: 
```
  ● Console

    console.error package/node_modules/fbjs/lib/warning.js:33
      Warning: Failed prop type: Invalid prop `content` of type `String` supplied to `CheckoutActionComplete`, expected instance of `Element`.
          in CheckoutActionComplete (at CheckoutActionComplete.test.js:14)```

**Comment by aldeed** [comment]
@kieckhafer @willopez To make it clear since `onChange` means something else in other components, can you change the `onChange` prop name to `onClickChangeButton`? Otherwise LGTM

**Comment by aldeed** [comment]
Also, I think @rymorgan decided we want to keep the step number on completed step labels. We could have the parent add it to `label` prop, but I think it's cleaner to add an optional `stepNumber` prop that gets added before the label identical to the `CheckoutActionIncomplete` component.

**Comment by rymorgan** [comment]
@aldeed Yes, we do want the numbers. I'm locked out of the uploading screens to the storefront zeplin project until @cassytaylor  gets back tomorrow but here are the designs for what that should look like. @kieckhafer, please reach out if you have questions. 

guest checkout - accordion - enter shipping address
guest checkout - accordion - shipping method
guest checkout - accordion - enter payment information
guest checkout - accordion - order review - on column

**Comment by willopez** [comment]
@aldeed @rymorgan I'll add the step numbers.

**Comment by rymorgan** [comment]
@willopez Awesome, thanks!

**Comment by willopez** [comment]
Reviewed  by @aldeed

**Pull request merged**
