### PR TITLE
(feat): 64 Checkbox Component

### LINKED ISSUE #64: Create checkbox component
**Summary**
Create a Checkbox component for the component library.

**Implementation**
The Checkbox component will follow the designs outlined in #19.

For this ticket, we're focused on implementing the vanilla checkbox and not the switch component or the radio buttons which are also outlined in #19.

**Acceptance Criteria**
- This will add a `Checkbox/v1` section to the component library
- The Checkbox will be included in the `Checkbox.js` file
- The Checkbox component be accompanied by documentation in the `Checkbox.md` file
- The Checkbox component will be well tested within the `Checkbox.test.js` file

### PR DESCRIPTION
**Pull request by nnnnat**
Resolves #64  
Impact: **major**  
Type: **feature**

## Component
- Add a CheckboxInput component based on these [specs](https://zpl.io/bzYjeKA).
- Accessibility: I added a light blue fuzzy border for the `:focus`
- Snyk: I'll rebase master as soon as snyk passes on master.

## Screenshots
Checked, unchecked, disabled
screen shot 2018-07-17 at 4 11 06 pm

Focus
screen shot 2018-07-17 at 4 20 57 pm

## URL
https://deploy-preview-78--stoic-hodgkin-c0179e.netlify.com/#!/Checkbox

## Testing
- Go to https://deploy-preview-78--stoic-hodgkin-c0179e.netlify.com/#!/Checkbox
- Use mouse to check and uncheck checkboxes
- Make sure disabled checkbox cannot be checked
- Use keyboard to check and uncheck checkboxes

### CODE REVIEW

**Comment by spencern** [comment]
@nnnnat do you want to try to hand this off to @machikoyasuda at some point?

**Comment by aldeed** [comment]
If it's helpful for figuring out the styles, here is some copypasta from another styled React checkbox component I once used. The styles objects would need to be translated into CSS.

```jsx
render() {
    const { style } = this.props;
    const { value } = this.state;
    const styles = { ...containerStyles, ...style };
    const checkStyles = { ...innerCheckboxStyles, opacity: value ? 1 : 0 };

    return (
      <div onClick={this.onClick} style={styles}>
        <div style={checkStyles}>
          <Icon name="checkmark" style={checkmarkStyles} />
        </div>
      </div>
    );
  }
```

```js
export const checkmarkStyles = {
  color: color.white,
  height: '100%',
  width: '100%',
};

export const containerStyles = {
    position: 'relative',
    fontSize: font.size.base,
    textAlign: 'left',
    backgroundColor: color.white,
    color: font.color.primary,
    borderColor: border.color,
    borderStyle: 'solid',
    borderWidth: border.width,
    borderBottomColor: border.color,
    borderBottomStyle: 'solid',
    borderTopLeftRadius: border.radius,
    borderTopRightRadius: border.radius,
    borderBottomLeftRadius: border.radius,
    borderBottomRightRadius: border.radius,
  height: '30px',
  width: '30px',
  cursor: 'pointer',
  paddingTop: '2px',
  paddingBottom: '2px',
  paddingLeft: '2px',
  paddingRight: '2px',
};

export const innerCheckboxStyles = {
  borderRadius: border.radius,
  backgroundColor: color.blue,
  height: '100%',
  width: '100%',
  transition: 'opacity 200ms ease',
  paddingTop: '2px',
  paddingBottom: '2px',
  paddingLeft: '2px',
  paddingRight: '2px',
};

```

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit b3590ed6a039d7108562fd9c4d53a4341cae6a75

https://deploy-preview-78--stoic-hodgkin-c0179e.netlify.com

**Comment by machikoyasuda** [comment]
@nnnnat - Can you review this the ole fashioned way? I can't add you officially as a reviewer, since you were the one that originally made the PR.

Review remarks:
- CSS style - I currently have `<StyledInput>`, `<StyledLabel>`, `<StyledDiv>` all as separate objects. Is it better to have them nested into 1 object like this example? https://github.com/styled-components/styled-components/issues/74#issuecomment-253654443
- CSS class names - Should they be named something more Checkbox-specific, like `<CheckboxInput>`, `<CheckboxLabel>`, `<CheckboxContainer>`?
- Any other tests to add?

**Comment by machikoyasuda** [comment]
@aldeed I accidentally messed with the files in `styleguide/src` ... I think while I was testing deployment (?!) in these commits: https://github.com/reactioncommerce/reaction-component-library/pull/78/commits/ac9c06725b937a3b66d78511bc8c8d57ea3df6e1 https://github.com/reactioncommerce/reaction-component-library/pull/78/commits/d85f41b9059ecb2fbf2b462fd412206f2f6297af

I tried reverting those commits, but couldn't get that without conflicts. Is it okay that these commits are there? The files aren't changed.

**Comment by machikoyasuda** [comment]
@aldeed Uh oh.. docker won't build because I seem to have borked my `package/yarn.lock` file. How do I update the package/yarn.lock file?

**Comment by machikoyasuda** [comment]
@rymorgan @nnnnat @aldeed Closing this PR in favor of https://github.com/reactioncommerce/reaction-component-library/pull/139 -- where I got package/yarn.lock right  ✔️

**Comment by nnnnat** [comment]
@machikoyasuda I believe that docker error was because of your lockfile and package.json were out of sync which would have happened if you merged master into your branch but had not run `yarn install`. All you should need to do is `cd package && yarn install` and push those changes

**Pull request closed without merging**
