### PR TITLE
fix: insecure package upgrade

### PR DESCRIPTION
**Pull request by mpaktiti**
Snyk reported a high severity vulnerability for this repo:
- **Vulnerable module**: lodash
- **Introduced through**: @reactioncommerce/components@0.0.0-development › react-select@2.4.4 › emotion@9.2.12 › babel-plugin-emotion@9.2.11 › @babel/helper-module-imports@7.0.0 › @babel/types@7.4.4 › lodash@4.17.11
- **Remediation**: Open Pull Request to patch lodash@4.17.11.

This PR re-creates `yarn.lock` to use the latest packages that do not include this lodash version. 

Note that my commit message starts with `fix` so this will trigger a new release, if we don't wanna do that, I can amend the message. 

Signed-off-by: Maria Paktiti <maria.paktiti@gmail.com>

### CODE REVIEW

**Comment by rc-publisher** [comment]
🚀 Preview deployed

Built with commit 57671ae75728fa0d053cef05a0e110d17d5273e9

https://deploy-preview-448--stoic-hodgkin-c0179e.netlify.com

**Comment by mpaktiti** [comment]
The build fails because snyk found 2 more vulnerabilities:

```
✗ Medium severity vulnerability found in mem
  Description: Denial of Service (DoS)
  Info: https://snyk.io/vuln/npm:mem:20180117
  Introduced through: libnpx@10.2.0
  From: libnpx@10.2.0 > yargs@11.1.0 > os-locale@2.1.0 > mem@1.1.0
  Remediation:
    Your dependencies are out of date, otherwise you would be using a newer version of mem. 
    Try deleting node_modules, reinstalling and running `snyk test` again. If the problem persists, one of your dependencies may be bundling outdated modules.

✗ Medium severity vulnerability found in https-proxy-agent
Description: Man-in-the-Middle (MitM)
  Info: https://snyk.io/vuln/SNYK-JS-HTTPSPROXYAGENT-469131
  Introduced through: libnpm@3.0.0, libcipm@4.0.0
  From: libnpm@3.0.0 > pacote@9.5.2 > make-fetch-happen@4.0.2 > https-proxy-agent@2.2.2
  From: libnpm@3.0.0 > npm-registry-fetch@3.9.1 > make-fetch-happen@4.0.2 > https-proxy-agent@2.2.2
  From: libcipm@4.0.0 > pacote@9.5.2 > make-fetch-happen@4.0.2 > https-proxy-agent@2.2.2
  and 9 more...
  Remediation:
    Your dependencies are out of date, otherwise you would be using a newer version of https-proxy-agent. 
    Try deleting node_modules, reinstalling and running `snyk test` again. If the problem persists, one of your dependencies may be bundling outdated modules.

Organisation:    ticean
Package manager: yarn
Target file:     package.json
Open source:     no
Project path:    /usr/local/src/reaction-app
Local Snyk policy: found

Tested 474 dependencies for known vulnerabilities, found 2 vulnerabilities, 13 vulnerable paths.
```

However when I run locally `snyk test` it reports 0 vulnerabilities.

**Comment by mikemurray** [comment]
@mpaktiti I approved, but I will not be able to merge until those two snyk issues are resolved. They can be ignored for 30days as I don't think there are resolutions for those issues.

**Comment by spencern** [comment]
@mikemurray or @mpaktiti do either of y'all want to fix our conflicts here and we can get this merged?

**Comment by mpaktiti** [comment]
I'm on it!

**Comment by mpaktiti** [comment]
@mikemurray The CI install-dependencies step fails with `semantic-release@15.13.30: The engine "node" is incompatible with this module. Expected version ">=8.16".`.
Do you know how to solve this? I saw recommendations online for `yarn install --ignore-engines`.

**Comment by aldeed** [comment]
@mpaktiti Try this:

In `.circleci/config.yml`, change `8.11.4-stretch` to `8.16.2-stretch`

**Comment by mpaktiti** [comment]
Thanks @aldeed that solved it!

@mikemurray Can you merge now?

**Pull request merged**
