### PR TITLE
(feat): 134 nnnnat cart items

### LINKED ISSUE #134: Unable to change Select value when it was provided one via props.
Type: **minor**

**Describe the bug**
When the Select component is provided a value via props you can not change the value of the field.

**To Reproduce**
1. Go to [staging](https://stoic-hodgkin-c0179e.netlify.com/#!/Select) scroll to the bottom of the page to the "Valid State" section
2. Click on Select and try to change the Input's value
4. The value will not update and the Select's dropdown will have the example code overlaying the select options.

**Expected behavior**
When the Select has been provided a value via props it should render with that value selected but also be changed when selecting a different option.

**Screenshots**
Code block overlay/z-index issue
screen shot 2018-07-17 at 9 55 40 am

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome 67 && firefox 61

### PR DESCRIPTION
**Pull request by nnnnat**
Resolves #134  
Impact: **major**  
Type: **feature**

## Component
Added a CartItems component based on these [specs](https://github.com/reactioncommerce/reaction-next-starterkit/issues/134)

## Screenshots
Desktop
screen shot 2018-06-29 at 12 59 59 pm

Mobile
screen shot 2018-06-29 at 1 02 53 pm

## Testing
1. Make sure it looks good and works

### CODE REVIEW

**Comment by rymorgan** [comment]
While I agree it doesn't look bad in this example, the issue is long Product Names. If the product name runs long then it will hurt readability b/c the names will have to break more aggressively. Long way of saying I think we should match the designs and push it down on mobile.

**Comment by nnnnat** [comment]
@kieckhafer  the CartItem does drop the price down to the bottom for mobile, I think the recent sidebar updates make the component smaller while the sidebar stays a fixed width causing the breakpoints to not line up as they should. If you size the browser size down so the sidebar goes away it should display correctly

**Comment by kieckhafer** [comment]
@nnnnat You're right, I was using mobile mode in the chrome dev-tools, and it was still on top. When looking at it on my actual phone, it was moved to the correct location, however... it doesn't looks great in that location on mobile, at least when there is a strike-through price, it's a bit crowded.

@rymorgan Thoughts on what to do here? Seems like the phone width might be narrower than the designs.

This might not be for this ticket either, maybe we make a new ticket to fix this.

img_7e3f85abdd8b-1

**Comment by nnnnat** [comment]
I just pushed a fixed for the rounded corners of the QuantityInput. @kieckhafer @rymorgan it def looks a little crowded for mobile. I think the StockWarning and Price components are rendering at 16px font size when they look to be 14px in zeplin fixing those font sizes should help.

**Comment by nnnnat** [comment]
I double checked all the CartItem fonts against the design and updated a few things.

screen shot 2018-07-02 at 3 32 28 pm

**Comment by kieckhafer** [comment]
Overall, this looks great. There are a few small UI issues that seem to be occurring, but they seem to be caused by the new design of the Component library itself, not this particular component.

I've created an issue, https://github.com/reactioncommerce/reaction-component-library/issues/114, to re-visit this and just make sure everything is working as it should once we pull this into the starterkit.

**Pull request merged**
