### PR TITLE
feat: add StripePaymentCheckoutAction component

### LINKED ISSUE #216: StripePaymentCheckoutAction
# StripePaymentCheckoutAction

## Overview / Summary
This component will be responsible for rendering the Stipe payment form, which is provided by the`StripeForm` component.  And it will render the completed view, which will display the user's information in read only form. Further, it will provide methods to elevate collected user data to containing component.

### PR DESCRIPTION
**Pull request by willopez**
Resolves #216 
Impact: normal
Type: feature

## Component
Adds a checkout action component to house the stripe payment form. Note: The "Use a different billing address" feature is not currently implemented, it's blocked `SelectableList` being completed.

## Testing
1. Enter a shipping address
2. Click on save and continue
3. Click on the "change" link for shipping address
4. Update shipping address
5. Verify change was saved
6. The "Payment information" step should be active
7. Enter a valid test payment info: CC: 4111 1111 1111 1111, valid expire date, any three numbers for cvc and a valid postal code.
8. Click on save and continue
9. Verify payment information was saved.

### CODE REVIEW

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit 3948c0a5c56029a7ac3856bfb54b8f6ece73d360

https://deploy-preview-217--stoic-hodgkin-c0179e.netlify.com

**Comment by willopez** [comment]
@nnnnat completed state docs added.

**Comment by nnnnat** [comment]
@willopez  I think this one is good 2 go if you can update it with master, since I merged #210  in we've got a few conflicts now

**Pull request merged**
