### PR TITLE
docs(type): add Typography docs

### LINKED ISSUE #142: Docs: Document and publish Type design guidelines
Document and publish Typography design guidelines

## Steps
1. Create a markdown file in the [`styleguide/src/sections/`](https://github.com/reactioncommerce/reaction-component-library/tree/master/styleguide/src/sections) folder by clicking [`Create a new file`](https://github.com/reactioncommerce/reaction-component-library/new/master/styleguide/src/sections)
2. Add guidelines into this markdown file
3. Scroll down and Click `Commit` with the `🔘 Create a new branch for this commit and start a pull request. ` turned on.
4. Keep editing that file.
5. Add the name of that file to the table of contents, here: https://github.com/reactioncommerce/reaction-component-library/blob/master/styleguide.config.js#L251

(Machiko can help with step #2)

## Content

- fontFamily
- font size scale
- font weights
- leading

### PR DESCRIPTION
**Pull request by machikoyasuda**
Resolves #142 
Impact: **minor**  
Type: **docs**

## Component
- Docs: Type

## Screenshots
https://deploy-preview-197--stoic-hodgkin-c0179e.netlify.com/#!/Typography

## Testing
1. Read https://deploy-preview-197--stoic-hodgkin-c0179e.netlify.com/#!/Typography + Compare with Zeplin

### CODE REVIEW

**Comment by machikoyasuda** [comment]
🚀 Preview deployed

Built with commit af7b2e49c132c4b26aa21cfd9467364530f1b39f

https://deploy-preview-197--stoic-hodgkin-c0179e.netlify.com

**Comment by machikoyasuda** [comment]
screen shot 2018-08-17 at 11 24 38 am
screen shot 2018-08-17 at 11 24 43 am
screen shot 2018-08-17 at 11 24 58 am
@cassytaylor fixes!!

**Comment by cassytaylor** [comment]
Looks great! Thank youuu

**Pull request merged**
