### PR TITLE
#84: style the component library

### LINKED ISSUE #84: Style the style guide
Need to adjust CSS, create some custom components, and add a standard header to make this look more like our www and docs sites.

Refer to:
- https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-styles-of-a-style-guide
- https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-the-layout-of-a-style-guide

- Sidebar
- Header bar
- Search bar
- Type font
- Code font
- `VIEW CODE`, `PROPS` text type
- Table type
- Code block type

### PR DESCRIPTION
**Pull request by machikoyasuda**
resolves #84 

## issue

- [x] Style the Header
- [x] Style the Sidenav
- [x] Style the Logo
- [x] Typography: code font
- [x] Typography: text font
- [x] Type element: Code block
- [x] Type element: Table
- [x] Type element: links, hovers

## screenshots

screen shot 2018-06-19 at 5 11 27 pm
screen shot 2018-06-19 at 5 16 39 pm
screen shot 2018-06-19 at 5 16 56 pm
screen shot 2018-06-19 at 5 16 59 pm

### CODE REVIEW

**Comment by machikoyasuda** [comment]
@rymorgan I'll post screenshots here of my WIP on this

**Comment by machikoyasuda** [comment]
@rymorgan I need styles for what links, hover links, other type stuff should look. Should I just pull them from the docs site style guide?

**Comment by machikoyasuda** [comment]
@aldeed Do you know why the CSS class name numbers randomly change? For example, `.rsg--header-11` changed to `.rsg--header-29` or some other number, after I refreshed. It makes it hard to overwrite the CSS.

Or should I be overwriting the CSS somewhere else?

**Comment by aldeed** [comment]
@machikoyasuda I think for those you may have to use the `styles` object described here: https://react-styleguidist.js.org/docs/cookbook.html#how-to-change-styles-of-a-style-guide

They are from React components that use JSS. You can either overwrite the whole component (which may eventually have to do for some) or you can overwrite just some styles in `styleguide.config.js` in `styles` object. This seems a bit annoying to me because you need to restart the app whenever you change that file.

It's not very well documented, so you might have to use React devtools browser extension to see what the component names are and then find them in the codebase in GitHub. Hopefully most of what you need to change can be done in the `theme`, though.

**Comment by machikoyasuda** [comment]
screen shot 2018-06-19 at 5 11 27 pm
screen shot 2018-06-19 at 5 16 39 pm
screen shot 2018-06-19 at 5 16 56 pm
screen shot 2018-06-19 at 5 16 59 pm
@aldeed @rymorgan  So far :point

**Comment by aldeed** [comment]
@machikoyasuda As long as you git remove and gitignore everything in `styleguide/reaction-component-library` before merging, I'm fine with merging this whenever you and Ryan think it's ready.

**Comment by rymorgan** [comment]
Considering it is iteration 1, and it's not public, I think we can merge now as well.

**Comment by machikoyasuda** [comment]
@aldeed I renamed the build folder to `dist`, and it's getting git-ignored correctly 👍

**Pull request merged**
